### ISSUE TITLE
Add Student with no Previous Withdrawals

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/uoj#22]

**Comment by michaelwebbjisc** [comment]
@amason - a query on this one.  I'm pretty sure all students have no previous withdrawals other than the one I explicitly added.

**Comment by amason** [comment]
@michaelwebbjisc Student ID 50922 should have 3 previous withdrawals...did you add it to that student? I just need the previou withdrawals to be >0. It looks like student id 50922 is still at 0. Can you have a look and let me know?

**Comment by amason** [comment]
This passes my QA. Closing as complete.
