### ISSUE TITLE
Additional Test Cases in Test Data

### ISSUE THREAD

**Issue by pspaude** [jiscdev/uoj#5]
Amanda wishes to test certain use-cases and as a result needs rougher data.  She needs a Student without a Tutor assigned. She also would like a student or two with key Risk Indicator data missing. I'll send this ticket to her so she can update with anything else she needs.

**Comment by amason** [comment]
@michaelwebbjisc

**Comment by michaelwebbjisc** [comment]
For 3) The UDD data is the source of truth, so it should revert to the UDD value.

**Comment by michaelwebbjisc** [comment]
For 1)

30071 and 30072 now don't have a tutor.

**Comment by michaelwebbjisc** [comment]
For 2) ...

30070 is now not enrolled on any modules

**Comment by michaelwebbjisc** [comment]
2 again: 3080 is now retaking two modules.

**Comment by michaelwebbjisc** [comment]
Can I check, are grade average and date of last graded work both a scenario where a student has not assessment instances?

**Comment by amason** [comment]
Here are the calculation for Grade Average and Date of LAst Graded Work: 

Grade Average 


    * If number <40, risk indicator should appear red in UI 
    * If number falls between range of 40 to 60, risk indicator should appear amber in UI 
    * If number is >60, risk indicator should appear green in UI 
    * Ensure green, amber and red colors are WCAG 2.0 AA compliant. WCAG requirements are 
        * Text and images of text have a contrast ratio of at least 4.5:1. 
        * Large text (over 18 point or 14 point bold) has a contrast ratio of at least 3:1 


Calculation Requirements 


    * Grade Average - this is the average (earned points/maxpoints* weight). The student assessment instance uses the ASSESS_SEQ_ID to the latest one and then will look at the ASSESS_ACTUAL_MARK 

Date of Last Graded Work 


    * Only text should display reflecting the Date of Last Graded Work. It should still behave as an alert, but do not color code this risk indicator in the UI 
    * The value of the Date of Last Graded Work will be changing often based on when the faculty last graded work 
    * Ensure text is WCAG 2.0 AA compliant. WCAG requirements are 
        * Text and images of text have a contrast ratio of at least 4.5:1. 
        * Large text (over 18 point or 14 point bold) has a contrast ratio of at least 3:1 


Calculation Requirements 


    * The value should be stored in the ASSESS_ACTUAL_MARK. This is the initial mark given for the assessment attempt. 

Let me know if that is what you were looking for. 

Amanda

**Comment by amason** [comment]
On this one Michael -"2 again: 3080 is now retaking two modules - am I correct in that this was a request to have a student with a retake, as most are already null."

Correct - the scenario I want to test is student who has retaken a module >1 time, so that will suffice.

**Comment by michaelwebbjisc** [comment]
2) again.. 30090  now has a course withdrawal

**Comment by amason** [comment]
Cool - Are the changes you are making real time or will the UDD file process load tonight at midnight? (Meaning, can I test these now or do I need to wait until tomorrow?)

**Comment by michaelwebbjisc** [comment]
Yes, real time.

**Comment by amason** [comment]
Perfect.

**Comment by amason** [comment]
Hey @michaelwebbjisc  We dont see 30071, 20072 or any of the others you listed in the UDD data. Are those student ids? Can you give us additional info to search by in the UDD?

**Comment by amason** [comment]
@michaelwebbjisc  One more question on #3 above. Since the UDD data is the source of truth, and if a change in SSP will revert it back to the UDD value...should we block users in SSP from changing the coach in SSP? If we leave the functionality the way it is today, I can see how some staff may get confused if they changed the personal tutor one day and the next day it overrides it with the original data. Let me know if you want us to lock down this feature so the assigned coach cant be changed in SSP.

**Comment by amason** [comment]
@michaelwebbjisc  Can I have you add >1 for retake count of the following student ids please for blue data: 50418,50926, 50422, 50356?

**Comment by amason** [comment]
@michaelwebbjisc As I'm continuing to test SSP, I'm noticing I need more data manipulation for some specific test cases. Let me put together the exact test cases I need so you can manipulate the data all at once. Once I have it ready, I'll place it in this github issue. Thanks!

**Comment by amason** [comment]
@michaelwebbjisc  - Here are the specific UoJ UDD data manipulations I need you to make:

1. In the UDD, Caroline Bowman, student ID 50049 should not be assigned a personal tutor. We will have SSP configured to have Beth Kim as the default coach in SSP. Test case is to make sure student id 50049 who came over in the UDD is assigned to the default coach, Beth Kim.

2. I need the following student data manipulated in the following manner
•	**Previous Withdrawals** – For student if 50922, I need previous withdrawals to be 3.
•	**Last Activity** – For student id 50922, I need the last activity date to be 1/23/2017. For student id. For student id 50882, I need the last activity date to be 1/13/2017. For student ID 50985, I need the data to be 12/15/2016.
•	**Grade Average** – for student ID 50419, I need the GAP to be 50. For student ID 50681, I need the GPA to be 82. This will help me test the color triggers in the UI.
•	**Retake Count** – For student ID 50419, I need the retake count to be 3. For student id 50779, I need the retake count to be 0. For student id 50711, I need the retake count to be 1.

**Comment by michaelwebbjisc** [comment]
Hi Amanda,

I'm closing this thread and reposting as single items so we can track it.

**Comment by amason** [comment]
@michaelwebbjisc You missed some scenarios. I'll open up individual github issues so it's easier to decipher. Can these modifications get done today? Thanks!
