### ISSUE TITLE
SSP Coaching History Download Report

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#6]
Hi @michaelwebbjisc 
Take a look at the PDF I attached here from SSP. Your current SSP version has an option for personal tutors to download the student summary and coaching history into a report but I'm seeing the following issues from a format perspective:

Issue 1 -Some of the headers are reading as Rhif Ffon Cartref, Ffon Symudol: and Rhif Ffon Arall: and those are obviously wrong and should not be listed as such.

Issue 2 -  Under the Success Indicators, I see header like this: i8n.riskindicators.Enrollment Count and i8n.riskindicators.Last Activity Time. We can take out the i8n.riskindicators. part and just list "Last Activity Time" but this will take some effort.

Issue 3 - Same thing for in the comments, I see this:
Comment: Summary: Early Alert Course: ART301 Early Alert Created Date: Tue Jan 17 18:55:55 UTC 2017 Response Created by: Duns Richards Response Details: Outcome: i8n.eaoutcomes.Student Responded Outreach: i8n.eaoutreach.In Person Referral: TEST Comment: Met with student in person. Crynodeb: Cwrs Hysbysiad Cynnar: ART301 Dyddiad Hysbysiad Cynar: Tue Jan 17 18:55:55 UTC 2017 Ymateb ganddo: $earlyAlertResponse.createdBy.firstName $earlyAlertResponse.createdBy.lastName Manylion Ymateb: Canlyniad: i8n.eaoutcomes.Student Responded Gwaith Ymestyn: $earlyAlertOutreach.name Cyfeiriad: $earlyAlertReferral.name Sylwadau: Met with student in person

Again, we can remove the odd characters such a $ and the i8n.eaoutreach.In Person Referral, but all of this is going to take a bit of work to clean up these issues. There's also a lot of blank fields in this report that don't pertain to the Jisc version of SSP.

Does it make sense for us to spend time going through this report and customizing it for the Jisc version of SSP OR should we remove this report from being downloaded in SSP? Personal Tutors are able to find this information in SSP so I dont know how valuable this report would be to a personal tutor anyway.
 
I can also ask Gloucestershire and Cardiff if they feel this would be a report they would want or not.

Let me know your thoughts and how you want me to proceed.
[Coaching_History_Report-Cunningham (1).pdf](https://github.com/jiscdev/uoj/files/727243/Coaching_History_Report-Cunningham.1.pdf)

**Comment by michaelwebbjisc** [comment]
Closed as not related to University of Jisc - pick up at weekly meetings.
