### ISSUE TITLE
Need Values 3 and 4 for Gender

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#7]
Hi @michaelwebbjisc 

The UDD specs indicates 4 possible values for Gender: 
Value 1 = Male
Value 2 = Female
Value 3 = Other
Value 4 = Unknown

In the blue data we are testing against, we have data for only #1 and #1 values.

Can you add gender value 3 to student id 50711 and gender value 4 for student id 50736?

**Comment by michaelwebbjisc** [comment]
Done
