### ISSUE TITLE
Discuss Creating a Process to Set Up S3 Buckets for SSP Document Backups

### ISSUE THREAD

**Issue by amason** [jiscdev/uoj#8]
Hey @michaelwebbjisc 

We should talk about setting up S3 buckets at the institution level to back up any SSP documents that are uploaded so that if documents are lost, they are backed up. I'm assuming this is something Jisc would want in place for each institution?

If so, we also need to discuss time parameters...how long should the documents live in S3?

**Comment by michaelwebbjisc** [comment]
Hi Amanda, This isn't related to University of Jisc - should be picked up in weekly meetings.
